### ISSUE TITLE
Feature suggestion: Support YAML

### ISSUE THREAD

**Issue by therealklanni** [stevelacy/mkdirj#1]
JSON to Dir is nice, but also supporting YAML to Dir would be even nicer :)

Just a suggestion!

**Comment by stevelacy** [comment]
What would the format be, just regular nested mappings?

**Comment by therealklanni** [comment]
Yeah, same format, just in yaml

```yml
dir:
- subdir:
   - subsubdir
- another
```
